### ISSUE TITLE
iOS Pod install 的时候报错

### ISSUE THREAD

**Issue by BokAugust** [TencentCloud/TPNS-Flutter-Plugin#1]
Cloning into '/var/folders/qk/6cm583w10kq0qdr4s5pfytqc0000gn/T/d20210115-51848-ux9jm3'...
fatal: could not read Username for 'https://git.code.tencent.com': Device not configured
Exception: Error running pod install
Exited (sigterm)

**Comment by BokAugust** [comment]
已经解决，去腾讯工蜂注册了账号才行，否则拖不下来pod。

**Comment by seekcx** [comment]
这种设计是哪个鬼才想出来的。发布出来不行吗

**Comment by ultronnet** [comment]
一个二进制包，还要登录clone。鬼才。想用户想疯了吧

**Comment by seekcx** [comment]
> 一个二进制包，还要登录clone。鬼才。想用户想疯了吧。
> 想不通这是居然是腾讯干出来的。反过来想想，嗯嗯，这事确实是腾讯干得出来的。

兄弟，我改用 mobpush 了，直接提供 flutter sdk，厂商通道还免费。

受不了腾讯这帮b恶心人。我特么几十个包就没有一个需要git加载的，pub解决了，发现pod又特么是私有的git，想出这种设计的真是鬼才。

**Comment by woaiso** [comment]
技术何苦为难技术
