### ISSUE TITLE
OPPO手机通知栏权限问题！

### ISSUE THREAD

**Issue by MaleWxt** [TencentCloud/TPNS-Flutter-Plugin#10]
/// TPNS-OPPO 依赖包版本在 1.1.5.1 及以上支持，系统 ColorOS 5.0 以上有效
      XgAndroidApi.enableOppoNotification();
      这个APi无法在应用注册推送时，打开OPPO通知栏设置。

**Comment by stevenxiaowen** [comment]
您好，请确认使用的 OPPO 手机 ColorOS 版本在 5.0 以上；此功能依赖于 OPPO 推送 SDK 实现，请确认已经正确集成 OPPO 厂商通道，并能注册 OPPO 厂商 Token 成功。

另外，请注意需在推送服务启动接口 startXg() 前调用此 enableOppoNotification() 接口，才能生效。

生效时弹窗效果如下：
![image](https://user-images.githubusercontent.com/34368490/124534812-96dc5b00-de47-11eb-9574-efa2e7a39900.png)
