### ISSUE TITLE
空安全问题

### ISSUE THREAD

**Issue by TonghuaLee** [TencentCloud/TPNS-Flutter-Plugin#14]
https://github.com/TencentCloud/TPNS-Flutter-Plugin/blob/a19e2a78fd7bff2d29cc11066768b41995188a7e/lib/tpns_flutter_plugin.dart#L98

这里几个值可能为空，会导致空类型转换错误
![image](https://user-images.githubusercontent.com/14800457/128658750-78d092cf-5e71-41a0-9089-90de5b2601c1.png)

**Comment by rockzuo-104** [comment]
您好 新版1.1.4已支持
