### ISSUE TITLE
引入了最新版tpns_flutter_plugin: ^1.1.0，pod install报错

### ISSUE THREAD

**Issue by donfo** [TencentCloud/TPNS-Flutter-Plugin#15]
引入了最新版tpns_flutter_plugin: ^1.1.0，pod install报错，请问题如何处理

`/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20/rbconfig.rb:229: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "TPNS-iOS":
  In snapshot (Podfile.lock):
    TPNS-iOS (= 1.3.3.0)

  In Podfile:
    tpns_flutter_plugin (from `.symlinks/plugins/tpns_flutter_plugin/ios`) was resolved to 1.0.7, which depends on
      TPNS-iOS (= 1.2.4.9)

Specs satisfying the `TPNS-iOS (= 1.3.3.0), TPNS-iOS (= 1.2.4.9)` dependency were found, but they required a higher minimum deployment target.

[!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.`

**Comment by rockzuo-104** [comment]
您好！您应该是用了pub.dev上的和我们同名的插件（非正式），接入请参考：https://github.com/TencentCloud/TPNS-Flutter-Plugin
