### ISSUE TITLE
mac版本报错

### ISSUE THREAD

**Issue by lijianqiang12** [TencentCloud/TPNS-Flutter-Plugin#17]
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method setEnableDebug on channel tpns_flutter_plugin)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method regPush on channel tpns_flutter_plugin)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>

**Comment by rockzuo-104** [comment]
您好，我们的flutter插件是基于移动端提供的插件，请问您是需要macOS平台的支持吗
