### ISSUE TITLE
iOS接入正常，Android报10030009应用不存在

### ISSUE THREAD

**Issue by Kurokitu** [TencentCloud/TPNS-Flutter-Plugin#18]
![image](https://user-images.githubusercontent.com/19619713/134489510-ca9496a5-7727-4978-839a-8a28f1b71983.png)

**Comment by stevenxiaowen** [comment]
您好，请问您的安卓应用推送服务 accessId 多少，是否有参考文档内容 [配置集群域名](https://github.com/TencentCloud/TPNS-Flutter-Plugin#%E9%9B%86%E7%BE%A4%E5%9F%9F%E5%90%8D%E9%85%8D%E7%BD%AE%E5%A6%82%E6%9E%9C%E6%82%A8%E7%9A%84%E5%BA%94%E7%94%A8%E9%9D%9E%E5%B9%BF%E5%B7%9E%E9%9B%86%E7%BE%A4%E8%AF%B7%E6%8C%89%E7%85%A7%E4%BB%A5%E4%B8%8B%E6%96%B9%E6%B3%95%E8%BF%9B%E8%A1%8C%E5%9F%9F%E5%90%8D%E9%85%8D%E7%BD%AE%E5%B9%BF%E5%B7%9E%E9%9B%86%E7%BE%A4%E8%AF%B7%E5%BF%BD%E7%95%A5) 呢？

**Comment by Kurokitu** [comment]
已解决
