### ISSUE TITLE
fcm token问题

### ISSUE THREAD

**Issue by chiluo** [TencentCloud/TPNS-Flutter-Plugin#2]
如果华为设备上同时有fcm服务，通过`getOtherPushToken()`获取的是fcm的token，但是调用`isFcmRom()`没有返回结果，我该如何判断这个token是fcm的token。
`isFcmRom()`是否有点问题？

**Comment by stevenxiaowen** [comment]
1. 您好，Flutter 插件中  isFcmRom 接口内部当前是空实现，无实际使用效果；

2. TPNS 推送在注册厂商通道时，会按照设备是否支持谷歌服务、设备品牌进行自动选择，无特别需求情况下，开发者不需要额外关心厂商选择；

3. 特别情况下，提供接口 `XgFlutterPlugin.otherPushType` 获取当前使用的厂商品牌字符串信息，使用示例如下：
```dart
String otherPushType = await XgFlutterPlugin.otherPushType;
print('otherpushType: $otherPushType');
```
