### ISSUE TITLE
Flutter SDK  2.8.0 新建后的项目，集成最新1.1.5 无法启动

### ISSUE THREAD

**Issue by lzdtech** [TencentCloud/TPNS-Flutter-Plugin#24]
在Flutter SDK  2.8.0 版本新建的项目，启动报错

Running "flutter pub get" in untitled...
Launching lib\main.dart on M2102K1C in debug mode...
Running Gradle task 'assembleDebug'...
E:\Projects\StudioProjects\untitled\android\app\src\debug\AndroidManifest.xml Error:
	Attribute meta-data#XG_V2_ACCESS_ID@value at AndroidManifest.xml requires a placeholder substitution but no value for <XG_ACCESS_ID> is provided.
E:\Projects\StudioProjects\untitled\android\app\src\debug\AndroidManifest.xml Error:
	Attribute meta-data#XG_V2_ACCESS_KEY@value at AndroidManifest.xml requires a placeholder substitution but no value for <XG_ACCESS_KEY> is provided.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by stevenxiaowen** [comment]
您好，看报错堆栈，您是否有在 android 应用目录的 build.gradle 文件中添加 manifestPlaceholders 呢，参考接入说明：
![image](https://user-images.githubusercontent.com/34368490/147431864-ac802f0f-a57d-4e9c-8075-0fac826a9a9a.png)
