### ISSUE TITLE
Android isFcmRom()没有实现

### ISSUE THREAD

**Issue by iwpz** [TencentCloud/TPNS-Flutter-Plugin#25]
源码里就是个空方法，await到一万年也不行的呀。

**Comment by stevenxiaowen** [comment]
您好，TPNS SDK 内部会自动判断是否使用 FCM，无需依赖 isFcmRom 方法实现；当设备支持谷歌服务、app 已接入 firebase-messaging 依赖，并在代码中调用接口 XgAndroidApi.enableOtherPush，SDK 将自动判断启动 FCM 推送。

**Comment by iwpz** [comment]
> 您好，TPNS SDK 内部会自动判断是否使用 FCM，无需依赖 isFcmRom 方法实现；当设备支持谷歌服务、app 已接入 firebase-messaging 依赖，并在代码中调用接口 XgAndroidApi.enableOtherPush，SDK 将自动判断启动 FCM 推送。

但是我们的业务中需要依赖isFcm方法进行一些其他的判断，这种留下空方法不返回的确造成了一点困扰的。我的确可以自己判断，但是TPNS提供了嘛，就是没有实现而已，集成进去至少省些功夫的。

**Comment by stevenxiaowen** [comment]
您好，目前评估 isFcm 的原生判断方法不够可靠，当前先决定暂时弃用此方法。为给您带来的不便感到十分抱歉

**Comment by iwpz** [comment]
> 您好，目前评估 isFcm 的原生判断方法不够可靠，当前先决定暂时弃用此方法。为给您带来的不便感到十分抱歉

好的，期待未来能有可靠的方法。但是sdk中也最好标注一下，毕竟一直await isFcm不返回的确造成了困扰。
