### ISSUE TITLE
Android 12 接入时出现问题

### ISSUE THREAD

**Issue by Kurokitu** [TencentCloud/TPNS-Flutter-Plugin#26]

**Comment by stevenxiaowen** [comment]
您好，请描述您遇到问题的具体信息；如果编译器提示 Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined 相关信息，可以在安卓应用 AndroidManifest 文件内添加以下节点：

<activity
        android:name="com.tencent.android.tpush.TpnsActivity"
        android:exported="true">
</activity>
