### ISSUE TITLE
极光离线推送依赖冲突

### ISSUE THREAD

**Issue by FlameLee** [TencentCloud/TPNS-Flutter-Plugin#31]
接入TPNS厂商离线推送，引入依赖与极光离线推送依赖冲突
报错：
Duplicate class com.xiaomi.push.service.w found in modules xiaomi-1.3.2.0-release-runtime.jar (com.tencent.tpns:xiaomi:1.3.2.0-release) and xiaomi-4.0.9-runtime.jar (cn.jiguang.sdk.plugin:xiaomi:4.0.9)

//极光离线 小米推送
implementation ('cn.jiguang.sdk.plugin:xiaomi:4.0.9')
//tpns 小米推送
implementation ('com.tencent.tpns:xiaomi:1.3.2.0-release')

**Comment by stevenxiaowen** [comment]
来自不同厂商的厂商 sdk ，当前请二选一即可。
