### ISSUE TITLE
啥时候可以升级下ios sdk呢？

### ISSUE THREAD

**Issue by honpery** [TencentCloud/TPNS-Flutter-Plugin#35]
`[TPNS] [DEBUG] 新版本的TPNS SDK已经发布, 你可以手动下载或者通过CocoaPods更新. 详情如下:{
	[currentSDKVersion] = 1.3.4.1;
	[newSDKVersion] = 1.3.9.1;
	[releaseSDKUrl] = https://log.tpns.tencent.com/v3/sdk/download/aU9TOjEuMy45LjE6VFBOUy1TREstaU9TOkNPUw==.zip;
	[releaseNote] = 1. 修复：修复已知问题。
2. 优化：替换上报域名，减少上报带宽消耗。;
	[releaseDate] = 2022-07-06 18:33:28
}`

**Comment by rockzuo-104** [comment]
您好，请升级到V1.1.7版本，谢谢！
iOS SDK目前插件最新版为1.3.9.0一般会滞后主SDK一个版本，请知悉！
