### ISSUE TITLE
和 IM 的 tim_ui_kit_push_plugin 有依赖冲突怎么解决呢？

### ISSUE THREAD

**Issue by hellohejinyu** [TencentCloud/TPNS-Flutter-Plugin#37]
![image](https://user-images.githubusercontent.com/8766034/182313055-a1ca60d9-2910-4e83-a41d-e509c6605ee0.png)

使用 TPNS 做厂家通道离线推送时，发现和腾讯云 IM 的离线推送有依赖冲突。这种情况该怎么处理呢？

**Comment by stevenxiaowen** [comment]
您好，相关厂商推送依赖请二选一，参考：https://cloud.tencent.com/document/product/269/75428#.E6.AD.A5.E9.AA.A45.EF.BC.9A.E9.9B.86.E6.88.90.E5.8E.82.E5.95.86.E6.8E.A8.E9.80.81-sdk
