### ISSUE TITLE
安卓机型, 在通知中心向左侧滑删掉一条消息时, 如果此时App在运行, 仍然会调用xgPushClickAction回调方法

### ISSUE THREAD

**Issue by openUmbrella** [TencentCloud/TPNS-Flutter-Plugin#41]
问题如标题.
补充一下: 如果有多条消息, 叠在一起之后. 向左滑动后清除所有通知消息, 此时xgPushClickAction的回调方法会调用很多次, 相当于点击了所有的消息.

**Comment by stevenxiaowen** [comment]
您好，可通过推送服务回调 xgPushClickAction 返回的参数 para 中获取字段值 actionType，返回0表示消息被点击，返回2表示消息被清除。您这个场景应该是触发了多个通知的返回2的场景。

**Comment by openUmbrella** [comment]
好的, 感谢
