### ISSUE TITLE
请问在未注册其他厂商通道的情况下，可以发送push notification吗？

### ISSUE THREAD

**Issue by 1057437122** [TencentCloud/TPNS-Flutter-Plugin#42]
我想使用腾讯云国际给中国大陆的应用发信息，但是我没有注册 其他厂商的通道（华为，小米，oppo等），请问可以直接给这些机型发送push notificaiton吗？

**Comment by stevenxiaowen** [comment]
您好，未接入其他厂商通道时，在较新、较高版本安卓设备上，当应用进程被杀时可能无法发送推送。
