### ISSUE TITLE
您好  使用tpns  flutter  sdk(1.2.0)  收到收到推送后  应用退到后台  此时再点击推送 

### ISSUE THREAD

**Issue by WFCN** [TencentCloud/TPNS-Flutter-Plugin#43]
收到收到推送后  应用退到后台  此时再点击推送 
Android(一加6手机  Android10)  点击后无法进行跳转  得手动点击进入app后才能跳转

Iphone( iPhone11Pro  IOS16.4 ) 杀死app后点击推送则会先进入指定页面再次进入首页  

请问这种情况有解决的办法儿吗

**Comment by stevenxiaowen** [comment]
您好，

1. 安卓端的问题现象，
-     在收到推送时直接点击推送（不退到后台），跳转正常吗？
-     其他手机有遇到相同问题现象吗？

2. iOS端的推送点击动作由开发者自行实现，您可以在点击回调接口内自行处理跳转逻辑，例如判断是冷启动时就先打开首页、再打开指定页面。

**Comment by WFCN** [comment]
> 

Android端问题
1,不退到后台 可以正常跳转   
2,这边测试机一加6  华为mate20  nov7都是这样的问题  其他品牌的没测   

tpns的后台华为通道是不是需要配置上启动类(目前没有配置启动类  推动动作是打开应用      上传不了图片  见谅)

**Comment by stevenxiaowen** [comment]
您好，请添加TPNS微信助手账号 TPNS_Push，提供一下您遇到现象的录屏，以及遇到问题现象时的SDK运行日志。日志可按如下方式获取：

SDK debug运行模式下，在控制台输入命令 adb logcat threadTime | grep 'TPush'，将问题现象时段的日志文本复制到 txt 文件中提供。
