### ISSUE TITLE
iOS想借助通知服务拓展来提升消息抵达率，没有找到范例

### ISSUE THREAD

**Issue by ericccg** [TencentCloud/TPNS-Flutter-Plugin#45]
iOS上想要借助通知服务扩展来提升抵达率，目前没有看到如何实现的示例
请问flutter是否支持通知服务拓展？

**Comment by rockzuo-104** [comment]
支持的呢，可以进入iOS目录Xcode打开Runner.xcworkspace创建通知扩展插件，具体可以参考：https://cloud.tencent.com/document/product/548/36667
