### ISSUE TITLE
ios 端，设置角标会把横幅也清空

### ISSUE THREAD

**Issue by lopo12123** [TencentCloud/TPNS-Flutter-Plugin#49]
我使用如下方法来设置应用角标并同步云端的角标数字，

```
static void setBadge([int badgeNum = 0]) {
  _instance.setBadge(badgeNum);
  _instance.setAppBadge(badgeNum);
}
```

在 iOS 上，我设置角标数为 0 的时候剩余的横幅似乎也会被清空掉

请问这个可以有办法避免吗

**Comment by lopo12123** [comment]
我看到文档里有这些方法，但是 futter 的插件并没有提供对应的方法

https://cloud.tencent.com/document/product/548/56091
![image](https://github.com/TencentCloud/TPNS-Flutter-Plugin/assets/59609929/3879f2d0-9f26-40e7-8475-e2bbddaec290)

还有这个方法，获取当前通知栏的条数，希望也能加在flutter的插件里，方便一些自定义功能的使用
![image](https://github.com/TencentCloud/TPNS-Flutter-Plugin/assets/59609929/1b4bd503-49b4-43f6-ae7d-711f83872b1b)

**Comment by rockzuo-104** [comment]
badgeNum传0会清除通知中心所有通知，如果不想清除其他通知传-1即可
