### ISSUE TITLE
推送

### ISSUE THREAD

**Issue by fuxiaoqiang** [TencentCloud/TPNS-Flutter-Plugin#5]
前台推送不是应该默认关闭的吗

**Comment by rockzuo-104** [comment]
您好，目前前台推送是默展示的，如需前提不展示请修改此行代码（completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert);）
我们下个版本会将前台展示样式开放出来，供客户自己选择哈！
