### ISSUE TITLE
升级flutter 3.16.0 后控制台出现报错  安卓端

### ISSUE THREAD

**Issue by lopo12123** [TencentCloud/TPNS-Flutter-Plugin#52]
![image](https://github.com/TencentCloud/TPNS-Flutter-Plugin/assets/59609929/de8f17ec-f177-4a1b-a733-c0cd6dc6df82)

我不是做安卓开发的，不知道这个错误会不会有什么影响

**Comment by lopo12123** [comment]
回退了 1.2.6 后好像还是有这个问题，可能是升级flutter 之后出现的问题？

**Comment by rockzuo-104** [comment]
可能原因是配置信息有误，请提供详细日志排查。
