### ISSUE TITLE
ios设备app在前台可以收到推送，app杀死之后收不到推送

### ISSUE THREAD

**Issue by JesseBlackman** [TencentCloud/TPNS-Flutter-Plugin#54]
环境版本
flutter: 3.16.7
tpns_flutter_plugin: V1.2.8

当打开app时可以收到推送，app关掉之后收不到推送，从腾讯推送后台统计看到这些消息状态为实际发送但是未抵达。
请问该如何解决？是配置的问题吗

**Comment by rockzuo-104** [comment]
app后台一般是APNs通道注册失败，可以检查下工程配置，或者开启TPNS debug日志(setEnableDebug)来协助排查问题。
