### ISSUE TITLE
tpns的Android原生SDK已经更新很多版本了,请问能不能更新一下flutter依赖的SDK版本

### ISSUE THREAD

**Issue by WFCN** [TencentCloud/TPNS-Flutter-Plugin#57]
问题1:
             如标题
问题2:
            集成1.3.0版本后,Oppo,小米都在报隐私安全问题,说小米pushSDK在用户未同意的情况下收集AndroidID,我看原生SDK的更新说明是增加了不收集AndroidID的配置,但是flutter的SDK没有对应的API,请问能跟进一下吗?
           

![image](https://github.com/TencentCloud/TPNS-Flutter-Plugin/assets/12468734/d733b5d0-ecee-491a-b6c2-8754d75a862c)

**Comment by rockzuo-104** [comment]
1.3.1版本已更新
