### ISSUE TITLE
希望iOS可以不用登陆账号clone到

### ISSUE THREAD

**Issue by shawerestart** [TencentCloud/TPNS-Flutter-Plugin#6]
RT

**Comment by rockzuo-104** [comment]
您好 请问您使用的是哪个仓库的插件呢，当前仓库操作是和您github操作一样的哈

**Comment by shawerestart** [comment]
TPNS的iOS native库在pod install的时候是需要登陆腾讯工蜂的Git去拉取，如果你没在terminal里拉一遍输入工蜂的账号密码的话是拉不下来的。
你可以试试清除本地git的user cache 试试，应该可以重现这个问题

**Comment by shawerestart** [comment]
> 您好 请问您使用的是哪个仓库的插件呢，当前仓库操作是和您github操作一样的哈

TPNS的iOS native库在pod install的时候是需要登陆腾讯工蜂的Git去拉取，如果你没在terminal里拉一遍输入工蜂的账号密码的话是拉不下来的。
你可以试试清除本地git的user cache 试试，应该可以重现这个问题

**Comment by wbToCode** [comment]
为什么要close这个问题呢，明明还是存在

**Comment by ZackTvZ** [comment]
请问下这个问题是要登入什么的account?

**Comment by rockzuo-104** [comment]
您可以使用最新1.1.2哈，新的库不依赖于工蜂账号了哦。
