### ISSUE TITLE
鸿蒙什么时候集成到 flutter sdk

### ISSUE THREAD

**Issue by jasonlau233** [TencentCloud/TPNS-Flutter-Plugin#61]

**Comment by rockzuo-104** [comment]
HarmonyOS NEXT版本集成需要集成对应的SDK哈，下载链接：https://console.cloud.tencent.com/tpns/sdkdownload

**Comment by whichname** [comment]
应该提供 HarmonyOS NEXT 版本的适配呀，总不能 HarmonyOS NEXT 就只能原生集成吧

**Comment by whichname** [comment]
@rockzuo-104
